version: '3'
services:
  api:
    image: rodrigoturatti/desafio-globo:latest
    restart: always
    ports:
      - "80:8000"
    networks:
      - globo

  curl:
    image: rodrigoturatti/curl-globo:latest
    restart: no
    depends_on:
      - api
    networks:
      - globo

networks:
  globo: