name: Docker Build and Publish
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'app/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker version to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        tags: |
          rodrigoturatti/desafio-globo:${{ github.run_number }}

    - name: Push Docker version Latest to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        tags: |
          rodrigoturatti/desafio-globo:latest